# Generated by Django 3.2.8 on 2022-06-30 02:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0002_alter_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 6, 30, 2, 55, 27, 272682, tzinfo=utc)),
        ),
    ]
