# Generated by Django 3.2.8 on 2022-07-01 02:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0003_alter_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 7, 1, 2, 38, 53, 226785, tzinfo=utc)),
        ),
    ]
